trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  ARM_TENANT_ID: $(ARM_TENANT_ID)

stages:
- stage: TerraformInitApply
  jobs:
  - job: DeployVMs
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - script: |
        terraform --version
      displayName: 'Check Terraform Version'
    - script: |
        terraform init
      displayName: 'Terraform Init'
    - script: |
        terraform validate
      displayName: 'Terraform Validate'
    - script: |
        terraform plan -out=tfplan
      displayName: 'Terraform Plan'
    - script: |
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Apply'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(ARM_TENANT_ID)